// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRfXCwoxFfBOfjKin6DbLtZPY52GFCtIE',
    appId: '1:923496674989:web:ea8c048987fa949ae43824',
    messagingSenderId: '923496674989',
    projectId: 'ebuy-96df3',
    authDomain: 'ebuy-96df3.firebaseapp.com',
    storageBucket: 'ebuy-96df3.appspot.com',
    measurementId: 'G-GS3HBY16XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnvzJxRSbFM45qZIx3A5X22U9aKEzddA',
    appId: '1:923496674989:android:67591a18c41fc089e43824',
    messagingSenderId: '923496674989',
    projectId: 'ebuy-96df3',
    storageBucket: 'ebuy-96df3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWPkWmAorOM81qSCeUuBszLB7obiGO-n8',
    appId: '1:923496674989:ios:32eff95c014dd63de43824',
    messagingSenderId: '923496674989',
    projectId: 'ebuy-96df3',
    storageBucket: 'ebuy-96df3.appspot.com',
    iosClientId: '923496674989-uec8c1dp5oddq87a66lbma0k4pimrnaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWPkWmAorOM81qSCeUuBszLB7obiGO-n8',
    appId: '1:923496674989:ios:32eff95c014dd63de43824',
    messagingSenderId: '923496674989',
    projectId: 'ebuy-96df3',
    storageBucket: 'ebuy-96df3.appspot.com',
    iosClientId: '923496674989-uec8c1dp5oddq87a66lbma0k4pimrnaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebuy',
  );
}
