// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEK5PfTWd3YyItalVzn2D0TZllj9zyEU',
    appId: '1:900153953394:web:633a5268422d048f1ac6eb',
    messagingSenderId: '900153953394',
    projectId: 'ebuy-21912',
    authDomain: 'ebuy-21912.firebaseapp.com',
    storageBucket: 'ebuy-21912.appspot.com',
    measurementId: 'G-1J600KLDLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtxkLKRW7CyvDdcXEP2--iDEPLusohhU',
    appId: '1:900153953394:android:ee0edb11bc64479a1ac6eb',
    messagingSenderId: '900153953394',
    projectId: 'ebuy-21912',
    storageBucket: 'ebuy-21912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx2XyMVrjEiWuqeuJkrhf0gTmWvIrtGm0',
    appId: '1:900153953394:ios:c052aa1570e6cc801ac6eb',
    messagingSenderId: '900153953394',
    projectId: 'ebuy-21912',
    storageBucket: 'ebuy-21912.appspot.com',
    iosClientId: '900153953394-blmqtcvppk2i7bi2d85o3leernjvdepe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx2XyMVrjEiWuqeuJkrhf0gTmWvIrtGm0',
    appId: '1:900153953394:ios:c052aa1570e6cc801ac6eb',
    messagingSenderId: '900153953394',
    projectId: 'ebuy-21912',
    storageBucket: 'ebuy-21912.appspot.com',
    iosClientId: '900153953394-blmqtcvppk2i7bi2d85o3leernjvdepe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebuy',
  );
}
